version: '3.8'

services:
  db:
    image: postgres
    restart: always
    hostname: '127.0.0.1'
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: aiohttp
      POSTGRES_USER: aiohttp
      POSTGRES_DB: aiohttp
