version: '3.8'
services:
  backend:
    build: .
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    expose:
      - '8000'
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db
  nginx:
    build: nginx
    ports:
      - '8080:80'
    depends_on:
      - backend

volumes:
  postgres_data: